### ISSUE TITLE
BioNGS background jobs (EXPERIMENTAL)

### ISSUE THREAD

**Issue by fstrozzi** [rjpbonnal/bioruby-ngs#16]
Initial code to integrate delayed_job in BioNGS is available at https://github.com/fstrozzi/bioruby-ngs/tree/jobs. 
"delay" method was checked on existing tasks and is working as expected, storing the objects to be run into the db.
jobs:start is OK and runs the object stored but jobs:schedule task still not working (no errors but delayed_job is not starting in background as expected). 
A small workaround was needed to run delayed_job, as the gem needs to work with Rails underneath.

To Do:
- make jobs:schedule task working properly
- write code to run existing tasks in background
- testing, testing and testing

**Comment by rjpbonnal** [comment]
great,
I'll look at it next days.
